### ISSUE TITLE
How to use Bmob to login user?

### ISSUE THREAD

**Issue by CollinDai** [stevenh47/lightrpgui#15]
How can I pass the username/password to Bmob and get the result? And what would be in the result?

**Comment by stevenh47** [comment]
Here is the doc from bmob:
http://docs.bmob.cn/data/Android/b_developdoc/doc/index.html#用户管理
**OR** do you want me to handle it?

**Comment by CollinDai** [comment]
Let me take a look at it. How much have we engaged with Bmob?

**Comment by CollinDai** [comment]
Oh BTW, my Bmob account: dpk1216@163.com

**Comment by stevenh47** [comment]
The plan is to fully depend on bmob so far and migrate to other services in the future.

Shared the bmob database with your account.
