### ISSUE TITLE
Add game tags

### ISSUE THREAD

**Issue by CollinDai** [stevenh47/lightrpgui#26]

**Comment by CollinDai** [comment]
@stevenh47 Can I get some Acceptance Criteria here? Not sure what the tags are. And if you already have some thoughts of what the AC should be for the other features you can add them too.

**Comment by stevenh47** [comment]
What do you mean by Acceptance Criteria? I defined some tags here:
lightrpgui/app/src/main/java/ui/com/lightrpg/lightrpgui/game/GameTag.java

**Comment by CollinDai** [comment]
I meant some specific requirements with regarding to the feature. Like as a user what you would expect this to work.

**Comment by stevenh47** [comment]
The tag will basically work as a category, but one game can have several tags, so when user click one tag, the game list will show games with this tag. A question is can the user select multiple tags at a time, WDYT?

**Comment by CollinDai** [comment]
should the tags only be shown on top of the online game list of both of the lists?

**Comment by stevenh47** [comment]
Only online game list
