### ISSUE TITLE
Got Error:(17, 46) error: package ui.com.lightrpg.lightrpgui.databinding does not exist

### ISSUE THREAD

**Issue by stevenh47** [stevenh47/lightrpgui#27]
When I build the project, I got 

D:\Codes\Android\lightrpgui\app\src\main\java\ui\com\lightrpg\lightrpgui\LoginActivity.java
Error:(17, 46) error: package ui.com.lightrpg.lightrpgui.databinding does not exist
Error:(28, 13) error: cannot find symbol class ActivityLoginBinding

Do you have any idea?

**Comment by CollinDai** [comment]
Can you let me see the full stacktrace?

**Comment by CollinDai** [comment]
I got it too, looks like a injection setup issue. Let me try fixing it
